/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-04 08:07:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>Metro Home Page</title>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("                <style>\r\n");
      out.write("                    .bg-cover {\r\n");
      out.write("                        background-image: url('https://png.pngtree.com/thumb_back/fh260/background/20240729/pngtree-yellow-train-in-budapest-metro-hungary-image_15933708.jpg');\r\n");
      out.write("                        background-size: cover;\r\n");
      out.write("                        background-position: center;\r\n");
      out.write("                        background-repeat: no-repeat;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .overlay {\r\n");
      out.write("                        background: rgba(0, 0, 0, 0.7);\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("                <style>\r\n");
      out.write("                    .font-arial {\r\n");
      out.write("                        font-family: Arial, sans-serif;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .font-georgia {\r\n");
      out.write("                        font-family: Georgia, serif;\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body class=\"bg-dark text-white bg-cover bg-center position-relative\" style=\"height: 100vh;\">\r\n");
      out.write("                <div class=\"overlay position-absolute top-0 start-0 w-100 h-100\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg  navbar-dark  \" style=\"background-color: rgb(249, 170, 51);\">\r\n");
      out.write("                    <div class=\"container-fluid \">\r\n");
      out.write("                        <a class=\"navbar-brand\">\r\n");
      out.write("                            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"xworkz logo\" style=\"max-height: 40px;\">\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                            data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("                            aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link btn btn-primary  text-light\" href=\"getUserRegistrationInfo\"> New\r\n");
      out.write("                                        User\r\n");
      out.write("                                        Registration</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link btn btn-primary font-georgia text-light\"\r\n");
      out.write("                                        href=\"getLoginPage\">Login</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div class=\"row w-100\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Image Section -->\r\n");
      out.write("                    <!-- <div class=\"col-md-6 py-5 mx-0  \">\r\n");
      out.write("                        <div id=\"imageCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("                            <div class=\"carousel-inner\">\r\n");
      out.write("                                <div class=\"carousel-item active\">\r\n");
      out.write("                                    <img src=\"https://www.prestigesouthernstar.info/images/prestige/metro-bangalore.webp\"\r\n");
      out.write("                                        class=\"d-block w-100\" alt=\"Registration image 1\"\r\n");
      out.write("                                        style=\"object-fit: cover; height: 50%;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"carousel-item\">\r\n");
      out.write("                                    <img src=\"https://png.pngtree.com/thumb_back/fh260/background/20230928/pngtree-a-green-and-white-metro-train-pull-into-a-station-image_13357538.jpg\"\r\n");
      out.write("                                        class=\"d-block w-100\" alt=\"Registration image 2\"\r\n");
      out.write("                                        style=\"object-fit: cover; height: 50%;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#imageCarousel\"\r\n");
      out.write("                                data-bs-slide=\"prev\">\r\n");
      out.write("                                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#imageCarousel\"\r\n");
      out.write("                                data-bs-slide=\"next\">\r\n");
      out.write("                                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Main Section -->\r\n");
      out.write("                    <div class=\"container position-relative mt-5 text-center\">\r\n");
      out.write("                        <h2 class=\"py-5 fw-bold fst-italic fs-4 text-primary\">Welcome to Namma Metro</h2>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Footer Section -->\r\n");
      out.write("                    <footer class=\" text-white py-3 fixed-bottom\" style=\"background-color: rgb(3, 54, 255);\">\r\n");
      out.write("                        <div class=\"container text-center\">\r\n");
      out.write("                            <p class=\"mb-1\">&copy; 2024 Metro Service. All rights reserved.</p>\r\n");
      out.write("                            <nav>\r\n");
      out.write("                                <a href=\"PrivacyPolicy.jsp\" class=\"text-white me-3\">Privacy Policy</a>\r\n");
      out.write("                                <a href=\"TermsOfService.jsp\" class=\"text-white me-3\">Terms of Service</a>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </footer>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Bootstrap JS -->\r\n");
      out.write("                    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
