/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-04 10:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProfileUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <html>\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("                <link rel=\"stylesheet\"\r\n");
      out.write("                    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("                <title>Government Metro Service Login</title>\r\n");
      out.write("            </head>\r\n");
      out.write("            <style>\r\n");
      out.write("                i {\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("\r\n");
      out.write("            <body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Navigation Bar -->\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: rgb(15, 15, 15);\">\r\n");
      out.write("                    <div class=\"container-fluid\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"getIndex\">\r\n");
      out.write("                                <img src=\"https://www.x-workz.in/Logo.png\" alt=\"xworkz logo\" style=\"max-height: 50px;\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                            data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("                            aria-label=\"Toggle navigation\">\r\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link btn btn-primary btn-outline-dark text-light\"\r\n");
      out.write("                                        href=\"getIndex\">Home</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link btn btn-primary btn-outline-dark text-light\"\r\n");
      out.write("                                        href=\"getAdminPageByMail?emailId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Back</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <h3 class=\"justify-content-center\" style=\"color: green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("                <h3 class=\"justify-content-center\" style=\"color: #ff5722\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row justify-content-center py-0 my-5\">\r\n");
      out.write("                    <div class=\"  col-12 col-md-6 \"> <!-- Increased card size -->\r\n");
      out.write("                        <div class=\"card p-5 mx-auto  rounded-0 shadow-lg hover-shadow-lg border-dark\"\r\n");
      out.write("                            style=\"background-color: rgba(231, 234, 248, 0.7);\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card-header text-center bg-transparent border-0\">\r\n");
      out.write("                                <h3 class=\"text-dark\">User Details</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4 text-center\">\r\n");
      out.write("                                <img src=\"getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.userImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Profile Image\"\r\n");
      out.write("                                    class=\"img-thumbnail rounded-circle shadow-lg border  border-warning\"\r\n");
      out.write("                                    style=\"width: 180px; height: 180px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"updateDetails\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                <input type=\"number\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 1: First Name, Last Name -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">First Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"fName\" name=\"firstName\" placeholder=\"Enter First Name\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onblur=\"fNameValidation()\">\r\n");
      out.write("                                        <span id=\"firstName\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Last Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"lName\" name=\"lastName\" placeholder=\"Enter Last Name\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            onblur=\"lNameValidation()\">\r\n");
      out.write("                                        <span id=\"lastName\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 2: Birth Date, Email ID -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Birth Date:</label>\r\n");
      out.write("                                        <input type=\"date\" id=\"birthDate\" name=\"birthdayDate\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.birthdayDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Email ID</label>\r\n");
      out.write("                                        <input type=\"email\" id=\"eId\" name=\"emailId\" placeholder=\"Enter Email Id\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\" onblur=\"checkEmail()\">\r\n");
      out.write("                                        <span id=\"emailId\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 3: Mobile Number, Password -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Mobile Number</label>\r\n");
      out.write("                                        <input type=\"tel\" id=\"mNumber\" name=\"mobileNumber\"\r\n");
      out.write("                                            placeholder=\"Enter Mobile Number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.mobileNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            onblur=\"checkMobileNumber()\">\r\n");
      out.write("                                        <span id=\"mobileNumber\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Password</label>\r\n");
      out.write("                                        <div class=\"input-group\">\r\n");
      out.write("                                            <input type=\"password\" id=\"pass\" name=\"password\"\r\n");
      out.write("                                                placeholder=\"Enter Password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                                class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                                onblur=\"checkPassword()\" />\r\n");
      out.write("                                            <button class=\"btn btn-outline-dark\" type=\"button\"\r\n");
      out.write("                                                onclick=\"myFunction()\">\r\n");
      out.write("                                                <i class=\"fa fa-eye\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span id=\"password\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 4: Confirm Password (Hidden) -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-3\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\" hidden>\r\n");
      out.write("                                        <label class=\"form-label\">Confirm Password</label>\r\n");
      out.write("                                        <input type=\"password\" id=\"cpass\" name=\"confirmPassword\"\r\n");
      out.write("                                            placeholder=\"Confirm Password\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            onblur=\"confirmPasswordValidation()\">\r\n");
      out.write("                                        <span id=\"confirmPassword\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">gender </label>\r\n");
      out.write("                                        <input type=\"text\" id=\"gen\" name=\"gender\" placeholder=\" Enter gender\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${metroDto.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\">\r\n");
      out.write("                                        <span id=\"gender\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 5: File Upload -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <label class=\"form-label\">Upload Profile Image</label>\r\n");
      out.write("                                        <input type=\"file\" id=\"file\" name=\"file\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Submit Button -->\r\n");
      out.write("                                <div class=\"text-center mt-4\">\r\n");
      out.write("                                    <button id=\"button\" type=\"submit\" class=\"btn btn-primary w-100 py-2 shadow\">Update\r\n");
      out.write("                                        Profile</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("                <!-- Footer -->\r\n");
      out.write("                <footer class=\" text-white text-center py-3 \" style=\"background-color: rgb(153, 166, 172);\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <nav>\r\n");
      out.write("                            <a href=\"#\" class=\"mx-2 text-white\">Privacy Policy</a>\r\n");
      out.write("                            <a href=\"#\" class=\"mx-2 text-white\">Terms of Service</a>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function fNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"fName\").value;\r\n");
      out.write("                        console.log(names);\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 3 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        } else if (/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:yellow;'>firstName cannot contain numbers.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:yellow;'>Must be between 4 & 25 characters.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function lNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"lName\").value;\r\n");
      out.write("                        console.log(names)\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 0 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"Disabled\");\r\n");
      out.write("                        } else if (/\\d/.test(names) || names.length < 1) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"<span style='color:yellow;'>Last name cannot be a number and must be atleast 1.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function checkPassword() {\r\n");
      out.write("                        var pass = document.getElementById(\"pass\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var password = document.getElementById(\"password\");\r\n");
      out.write("\r\n");
      out.write("                        if (pass.trim !== '' && pass.length >= 8 && pass.length <= 12) {\r\n");
      out.write("                            password.innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\")\r\n");
      out.write("                        } else {\r\n");
      out.write("                            password.innerHTML = \"<span> password must have atleast 8 letters </span>\";\r\n");
      out.write("                            button.setAttribute(\"disabld\", \"\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    const checkMobileNumber = async () => {\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var mobileNumber = document.getElementById(\"mobileNumber\");\r\n");
      out.write("                        if (mNumber.length < 10 || mNumber.length > 10) {\r\n");
      out.write("                            mobileNumber.innerHTML = \"<span style='color:yellow'> Mobile Number length should be 10</span>\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            var response = await axios('http://localhost:8083/metro-application/isMobileNumberExists?mobileNumber=' + mNumber);\r\n");
      out.write("                            if (response.data === \"Mobile Number Exists\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"<span style='color:yellow'> Mobile Number Exists</span>\";\r\n");
      out.write("                                button.removeAttribute(\"disabled\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if (response.data === \"Mobile Number Accepted\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"\";\r\n");
      out.write("                                button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    const checkEmail = async () => {\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var response = await axios('http://localhost:8083/metro-application/isEmailExists?emailId=' + email);\r\n");
      out.write("                        if (response.data === \"Email Exists\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"<span style ='color:yellow'> Email exists </span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("\r\n");
      out.write("                        } else if (response.data === \"Email Accepted\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function myFunction() {\r\n");
      out.write("                        var x = document.getElementById(\"pass\");\r\n");
      out.write("                        if (x.type === \"password\") {\r\n");
      out.write("                            x.type = \"text\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            x.type = \"password\";\r\n");
      out.write("                        }\r\n");
      out.write("                    } \r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
