/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-04 09:40:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <html>\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"ISO-8859-1\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("                <title>Registration Page</title>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body class=\"bg-light text-dark\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Full Mask Overlay -->\r\n");
      out.write("                <!-- <div class=\"position-absolute top-0 start-0 w-100 h-100\" style=\"background-color: rgba(0, 0, 0, 0.7);\">\r\n");
      out.write("                </div> -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Navbar -->\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: rgb(127, 134, 138);\">\r\n");
      out.write("                    <div class=\"container-fluid d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"getIndex\">\r\n");
      out.write("                                <img src=\"https://www.x-workz.in/Logo.png\" alt=\"xworkz logo\" style=\"max-height: 50px;\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"navbar-text h5 text-dark  \">Government Metro Registratioin </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <li class=\"btn btn-primary btn-outline-dark\">\r\n");
      out.write("                                <a class=\"nav-link text-light \" href=\"getIndex\">Home</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container-fluid  col-md-6  align-items-center py-3  \">\r\n");
      out.write("                    <div class=\"card  rounded-0 text-dark shadow border-dark\"\r\n");
      out.write("                        style=\" padding: 20px 15px;\">\r\n");
      out.write("                        <h5 class=\"text-center  justify-content-end \" style=\"color: #ff5722;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registrationMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                        <div class=\"card-body p-3\">\r\n");
      out.write("                            <h2 class=\"text-center text-warning mb-3\">User Registration Form</h2>\r\n");
      out.write("                            <form action=\"onSaveRegistration\" method=\"post\" onblur=\"form()\">\r\n");
      out.write("                                <span id=\"formMessage\"></span>\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"text\" class=\"form-control rounded-0 \" id=\"id\" placeholder=\"Enter your id\" name=\"id\"\r\n");
      out.write("                                    hidden>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 1: First Name, Last Name -->\r\n");
      out.write("                                <div class=\"row mb-2\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">First Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"fName\" name=\"firstName\" placeholder=\"Enter First Name\"\r\n");
      out.write("                                            class=\"form-control rounded-0 border-dark\" onblur=\"fNameValidation()\" required>\r\n");
      out.write("                                        <span id=\"firstName\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Last Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"lName\" name=\"lastName\" placeholder=\"Enter Last Name\"\r\n");
      out.write("                                            class=\"form-control rounded-0 border-dark\" onblur=\"lNameValidation()\" required>\r\n");
      out.write("                                        <span id=\"lastName\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 2: Birthday, Gender -->\r\n");
      out.write("                                <div class=\"row mb-2\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label \">Birth Date:</label>\r\n");
      out.write("                                        <input type=\"date\" id=\"birthDate\" name=\"birthdayDate\" class=\"form-control rounded-0 border-dark\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-md-6 rounded-0 border-dark\">\r\n");
      out.write("                                        <label class=\"form-label d-block  \">Gender</label>\r\n");
      out.write("                                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                            <input class=\"form-check-input  border-dark \" type=\"radio\" name=\"gender\" id=\"femaleGender\"\r\n");
      out.write("                                                value=\"Female\" required>\r\n");
      out.write("                                            <label class=\"form-check-label\" for=\"femaleGender\">Female</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                            <input class=\"form-check-input  border-dark \" type=\"radio\" name=\"gender\" id=\"maleGender\"\r\n");
      out.write("                                                value=\"Male\">\r\n");
      out.write("                                            <label class=\"form-check-label\" for=\"maleGender\">Male</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                            <input class=\"form-check-input border-dark\" type=\"radio\" name=\"gender\" id=\"otherGender\"\r\n");
      out.write("                                                value=\"Other\">\r\n");
      out.write("                                            <label class=\"form-check-label \" for=\"otherGender\">Other</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span id=\"gender\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 3: Mobile Number, Email ID -->\r\n");
      out.write("                                <div class=\"row mb-2\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Email ID</label>\r\n");
      out.write("                                        <input type=\"email\" id=\"eId\" name=\"emailId\" placeholder=\"Enter e-mail id\"\r\n");
      out.write("                                            class=\"form-control rounded-0 border-dark\" onblur=\"checkEmail()\" required>\r\n");
      out.write("                                        <span id=\"emailId\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Mobile Number</label>\r\n");
      out.write("                                        <input type=\"tel\" id=\"mNumber\" name=\"mobileNumber\"\r\n");
      out.write("                                            placeholder=\"Enter mobile number\" class=\"form-control rounded-0 border-dark\"\r\n");
      out.write("                                            onblur=\"checkMobileNumber()\" required>\r\n");
      out.write("                                        <span id=\"mobileNumber\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 5: Password, Confirm Password -->\r\n");
      out.write("                                <div class=\"row mb-2\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Password</label>\r\n");
      out.write("                                        <input type=\"password\" id=\"pass\" name=\"password\" placeholder=\"Enter password\"\r\n");
      out.write("                                            class=\"form-control rounded-0 border-dark\" onblur=\"checkPassword()\" required>\r\n");
      out.write("                                        <span id=\"password\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Confirm Password</label>\r\n");
      out.write("                                        <input type=\"password\" id=\"cpass\" placeholder=\"Confirm password\"\r\n");
      out.write("                                            class=\"form-control rounded-0 border-dark\" onblur=\"confirmPassword()\" required>\r\n");
      out.write("                                        <span id=\"cPassword\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Submit Button -->\r\n");
      out.write("                                <div class=\"text-center mt-3\">\r\n");
      out.write("                                    <button id=\"button\" type=\"submit\" class=\"btn btn-primary w-100 rounded-0 border-dark\">Submit</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-2 text-center text-dark justify-content-center   \">\r\n");
      out.write("                            Already have an account? <a href=\"LoginByEmail.jsp\" class=\"text-warning mx-2\">Login</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("                <footer class=\" text-white py-3\" style=\"background-color: rgb(133, 128, 139);\">\r\n");
      out.write("                    <div class=\"container text-center\">\r\n");
      out.write("                        <p class=\"mb-1\">&copy; 2024 Metro Service. All rights reserved.</p>\r\n");
      out.write("                        <nav>\r\n");
      out.write("                            <a href=\"PrivacyPolicy.jsp\" class=\"text-white me-3\">Privacy Policy</a>\r\n");
      out.write("                            <a href=\"TermsOfService.jsp\" class=\"text-white me-3\">Terms of Service</a>\r\n");
      out.write("                            <a href=\"Support.jsp\" class=\"text-white\">Support</a>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("\r\n");
      out.write("                <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function fNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"fName\").value;\r\n");
      out.write("\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 3 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"\";\r\n");
      out.write("                        } else if (/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:red;'>First Name cannot contain numbers.</span>\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:red;'>Must be between 4 & 25 characters.</span>\";\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function lNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"lName\").value;\r\n");
      out.write("\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 0 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"\";\r\n");
      out.write("                        } else if (/\\d/.test(names) || names.length < 1) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"<span style='color:red;'>Last name cannot be a number and must be atleast 1.</span>\";\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    function checkPassword() {\r\n");
      out.write("                        var pass = document.getElementById(\"pass\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var password = document.getElementById(\"password\");\r\n");
      out.write("\r\n");
      out.write("                        if (pass.trim !== '' && pass.length >= 8 && pass.length <= 12) {\r\n");
      out.write("                            password.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("                        } else {\r\n");
      out.write("                            password.innerHTML = \"<span> password must have atleast 8 letters </span>\";\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function confirmPassword() {\r\n");
      out.write("                        const pass = document.getElementById(\"pass\").value;\r\n");
      out.write("                        const cpass = document.getElementById(\"cpass\").value;\r\n");
      out.write("                        const button = document.getElementById(\"button\");\r\n");
      out.write("                        const confirmPasswordMessage = document.getElementById(\"cPassword\");\r\n");
      out.write("                        confirmPasswordMessage.innerHTML = \"\";\r\n");
      out.write("                        if (cpass.trim() === '') {\r\n");
      out.write("                            confirmPasswordMessage.innerHTML = \"<span style='color:red;'>Password cannot be empty.</span>\";\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        if (cpass.length < 8 || cpass.length > 12) {\r\n");
      out.write("                            confirmPasswordMessage.innerHTML = \"<span style='color:red;'>Password must be between 8 and 12 characters.</span>\";\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        if (pass === cpass) {\r\n");
      out.write("                            confirmPasswordMessage.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("                        } else {\r\n");
      out.write("                            confirmPasswordMessage.innerHTML = \"<span style='color:red;'>Passwords do not match.</span>\";\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("                    const checkMobileNumber = async () => {\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var mobileNumber = document.getElementById(\"mobileNumber\");\r\n");
      out.write("\r\n");
      out.write("                        if (!(mNumber.length == 10)) {\r\n");
      out.write("                            mobileNumber.innerHTML = \"<span style='color:red'>Mobile Number length should be 10</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            var response = await axios('http://localhost:8083/metro-application/isMobileNumberExists?mobileNumber=' + mNumber);\r\n");
      out.write("                            if (response.data === \"Mobile Number Exists\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"<span style='color:red'>Mobile Number Exists</span>\";\r\n");
      out.write("                                button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                            } else if (response.data === \"Mobile Number Accepted\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"\";\r\n");
      out.write("                                checkForm();\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    const checkEmail = async () => {\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var response = await axios('http://localhost:8083/metro-application/isEmailExists?emailId=' + email);\r\n");
      out.write("                        if (response.data === \"Email Exists\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"<span style='color:red'>Email exists</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                        } else if (response.data === \"Email Accepted\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"\";\r\n");
      out.write("                            checkForm();\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function checkForm() {\r\n");
      out.write("                        var names = document.getElementById(\"fName\").value;\r\n");
      out.write("                        var lnames = document.getElementById(\"lName\").value;\r\n");
      out.write("                        var pass = document.getElementById(\"pass\").value;\r\n");
      out.write("                        const cpass = document.getElementById(\"cpass\").value;\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        if ((names.trim() !== '' && names.length > 3 && names.length <= 25 && !/\\d/.test(names)) &&\r\n");
      out.write("                            (lnames.trim() !== '' && lnames.length > 0 && lnames.length <= 25 && !/\\d/.test(lnames)) &&\r\n");
      out.write("                            (pass.trim() !== '' && pass.length >= 8 && pass.length <= 12 && pass === cpass) &&\r\n");
      out.write("                            (mNumber.length == 10) &&\r\n");
      out.write("                            (email.trim() !== \"\")\r\n");
      out.write("                        ) {\r\n");
      out.write("                            button.removeAttribute(\"disabled\")\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"formMessage\").innerHTML = \"\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
