/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-04 08:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserRegistrationInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <html>\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"ISO-8859-1\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("                <title>Registration Page</title>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body class=\"text-light\" style=\"background-color: rgb(173, 187, 187);\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Navbar -->\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: rgb(127, 134, 138);\">\r\n");
      out.write("                    <div class=\"container-fluid d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"getIndex\">\r\n");
      out.write("                                <img src=\"https://www.x-workz.in/Logo.png\" alt=\"xworkz logo\" style=\"max-height: 50px;\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"navbar-text h5 text-dark\">Government Metro Registration</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <li class=\"btn btn-primary font-georgia text-light\" >\r\n");
      out.write("                                <a class=\"nav-link \" href=\"getIndex\">Home</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    <!-- Registration Card Section -->\r\n");
      out.write("                    <div class=\"col-md-6 d-flex align-items-center py-5\">\r\n");
      out.write("                        <div class=\"card rounded-0 text-dark w-100\"\r\n");
      out.write("                            style=\"background-color: rgb(232, 245, 245); padding: 10px 15px;\">\r\n");
      out.write("                            <h5 class=\"text-center \" style=\"color: #ff5722;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfoMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                            <div class=\"card-body p-3\">\r\n");
      out.write("                                <h2 class=\"text-center mb-3\">User Registration Form</h2>\r\n");
      out.write("                                <form action=\"saveUserInfo\" method=\"post\" onblur=\"form()\">\r\n");
      out.write("                                    <span id=\"formMessage\"></span>\r\n");
      out.write("\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"id\" placeholder=\"Enter your id\"\r\n");
      out.write("                                        name=\"id\" hidden>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Row 1: First Name, Last Name -->\r\n");
      out.write("                                    <div class=\"row mb-2\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">First Name</label>\r\n");
      out.write("                                            <input type=\"text\" id=\"fName\" name=\"firstName\"\r\n");
      out.write("                                                placeholder=\"Enter First Name\" class=\"form-control\"\r\n");
      out.write("                                                onblur=\"fNameValidation()\" required>\r\n");
      out.write("                                            <span id=\"firstName\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Last Name</label>\r\n");
      out.write("                                            <input type=\"text\" id=\"lName\" name=\"lastName\" placeholder=\"Enter Last Name\"\r\n");
      out.write("                                                class=\"form-control\" onblur=\"lNameValidation()\" required>\r\n");
      out.write("                                            <span id=\"lastName\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Row 2: Birthday, Gender -->\r\n");
      out.write("                                    <div class=\"row mb-2\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Birth Date:</label>\r\n");
      out.write("                                            <input type=\"date\" id=\"birthDate\" name=\"birthdayDate\" class=\"form-control\">\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label d-block\">Gender</label>\r\n");
      out.write("                                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                                <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                                                    id=\"femaleGender\" value=\"Female\" required>\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"femaleGender\">Female</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                                <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                                                    id=\"maleGender\" value=\"Male\">\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"maleGender\">Male</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                                <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                                                    id=\"otherGender\" value=\"Other\">\r\n");
      out.write("                                                <label class=\"form-check-label\" for=\"otherGender\">Other</label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <span id=\"gender\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Row 3: Mobile Number, Email ID -->\r\n");
      out.write("                                    <div class=\"row mb-2\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Email ID</label>\r\n");
      out.write("                                            <input type=\"email\" id=\"eId\" name=\"emailId\" placeholder=\"Enter e-mail id\"\r\n");
      out.write("                                                class=\"form-control\" onblur=\"checkEmail()\" required>\r\n");
      out.write("                                            <span id=\"emailId\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Mobile Number</label>\r\n");
      out.write("                                            <input type=\"tel\" id=\"mNumber\" name=\"mobileNumber\"\r\n");
      out.write("                                                placeholder=\"Enter mobile number\" class=\"form-control\"\r\n");
      out.write("                                                onblur=\"checkMobileNumber()\" required>\r\n");
      out.write("                                            <span id=\"mobileNumber\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Row 5: Password, Confirm Password\r\n");
      out.write("                                    <div class=\"row mb-2\">\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Password</label>\r\n");
      out.write("                                            <input type=\"password\" id=\"pass\" name=\"password\"\r\n");
      out.write("                                                placeholder=\"Enter password\" class=\"form-control\"\r\n");
      out.write("                                                onblur=\"checkPassword()\" required>\r\n");
      out.write("                                            <span id=\"password\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">Confirm Password</label>\r\n");
      out.write("                                            <input type=\"password\" id=\"cpass\" placeholder=\"Confirm password\"\r\n");
      out.write("                                                class=\"form-control\" onblur=\"confirmPassword()\" required>\r\n");
      out.write("                                            <span id=\"cPassword\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div> -->\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Submit Button -->\r\n");
      out.write("                                    <div class=\"text-center mt-3\">\r\n");
      out.write("                                        <button id=\"button\" type=\"submit\" class=\"btn btn-primary w-100\">Submit</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </form>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-2 text-center text-dark justify-content-center\">\r\n");
      out.write("                                Already have an account? <a href=\"LoginByEmail.jsp\" class=\"text-warning mx-2\">Login</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <footer class=\" text-white py-3\" style=\"background-color: rgb(133, 128, 139); margin: 0;\">\r\n");
      out.write("                    <div class=\"container-fluid d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <p class=\"mb-1\">&copy; 2024 Metro Service. All rights reserved.</p>\r\n");
      out.write("                        <nav class=\"d-flex\">\r\n");
      out.write("                            <a href=\"PrivacyPolicy.jsp\" class=\"text-white me-3\">Privacy Policy</a>\r\n");
      out.write("                            <a href=\"TermsOfService.jsp\" class=\"text-white me-3\">Terms of Service</a>\r\n");
      out.write("                            <a href=\"Support.jsp\" class=\"text-white\">Support</a>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("\r\n");
      out.write("                <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function fNameValidation() {\r\n");
      out.write("                        var fname = document.getElementById(\"fName\").value\r\n");
      out.write("                        if (fname.trim() !== '' && fname.length > 3 && fname.length <= 25 && !/\\d/.test(fname)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"\";\r\n");
      out.write("                        } else if (/\\d/.test(fname)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:red;'>First Name cannot contain numbers.</span>\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:red;'>Must be between 4 & 25 characters.</span>\";\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("                    function lNameValidation(){\r\n");
      out.write("                        var lname = document.getElementById(\"lName\").value;\r\n");
      out.write("                        \r\n");
      out.write("                        if (names.trim() !== '' && names.length > 0 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"\";\r\n");
      out.write("                        } else if (/\\d/.test(names) || names.length < 1) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"<span style='color:red;'>Last name cannot be a number and must be atleast 1.</span>\";\r\n");
      out.write("                        }\r\n");
      out.write("                        checkForm();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    const checkMobileNumber = async () => {\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var mobileNumber = document.getElementById(\"mobileNumber\");\r\n");
      out.write("\r\n");
      out.write("                        if (!(mNumber.length == 10)) {\r\n");
      out.write("                            mobileNumber.innerHTML = \"<span style='color:red'>Mobile Number length should be 10</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            var response = await axios('http://localhost:8083/metro-application/isMobileNoExists?mobileNumber=' + mNumber);\r\n");
      out.write("                            if (response.data === \"Mobile Number Exists\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"<span style='color:red'>Mobile Number Exists</span>\";\r\n");
      out.write("                                button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                            } else if (response.data === \"Mobile Number Accepted\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"\";\r\n");
      out.write("                                checkForm();\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    const checkEmail = async () => {\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var response = await axios('http://localhost:8083/metro-application/isUserEmailExists?emailId=' + email);\r\n");
      out.write("                        if (response.data === \"Email Exists\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"<span style='color:red'>Email exists</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"disabled\");\r\n");
      out.write("                        } else if (response.data === \"Email Accepted\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"\";\r\n");
      out.write("                            checkForm();\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function checkForm() {\r\n");
      out.write("                        var names = document.getElementById(\"fName\").value;\r\n");
      out.write("                        var lnames = document.getElementById(\"lName\").value;\r\n");
      out.write("                        var pass = document.getElementById(\"pass\").value;\r\n");
      out.write("                        const cpass = document.getElementById(\"cpass\").value;\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        if ((names.trim() !== '' && names.length > 3 && names.length <= 25 && !/\\d/.test(names)) &&\r\n");
      out.write("                            (lnames.trim() !== '' && lnames.length > 0 && lnames.length <= 25 && !/\\d/.test(lnames)) &&\r\n");
      out.write("                            (pass.trim() !== '' && pass.length >= 8 && pass.length <= 12 && pass === cpass) &&\r\n");
      out.write("                            (mNumber.length == 10) &&\r\n");
      out.write("                            (email.trim() !== \"\")\r\n");
      out.write("                        ) {\r\n");
      out.write("                            button.removeAttribute(\"disabled\")\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"formMessage\").innerHTML = \"\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
