/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-23 11:04:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserProfileUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <html>\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("                <link rel=\"stylesheet\"\r\n");
      out.write("                    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("                <title>Government Metro Service Login</title>\r\n");
      out.write("            </head>\r\n");
      out.write("            <style>\r\n");
      out.write("                i {\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("\r\n");
      out.write("            <body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <nav class=\"navbar navbar-expand-lg navbar-dark vw-100\" style=\"background-color: rgb(13, 16, 19);\">\r\n");
      out.write("                        <div class=\"container-fluid\">\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"getIndex\">\r\n");
      out.write("                                <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Company Logo\" style=\"max-height: 40px;\">\r\n");
      out.write("                            </a>\r\n");
      out.write("\r\n");
      out.write("                            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                                data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"\r\n");
      out.write("                                aria-label=\"Toggle navigation\">\r\n");
      out.write("                                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                                <ul class=\"navbar-nav ms-auto text-center align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                                    <li class=\"nav-item mx-auto\">\r\n");
      out.write("                                        <img src=\"getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.userImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"User Image\"\r\n");
      out.write("                                            class=\"rounded-circle border border-warning shadow-sm\"\r\n");
      out.write("                                            style=\"width: 50px; height: 50px; cursor: pointer;\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                            data-bs-target=\"#profileImageModal\">\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item mx-3\">\r\n");
      out.write("                                        <a class=\"nav-link btn btn-primary text-light\"\r\n");
      out.write("                                            href=\"getBookingPage?emailId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Book\r\n");
      out.write("                                            Ticket</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item mx-3\">\r\n");
      out.write("                                        <a class=\"nav-link btn btn-primary text-light\"\r\n");
      out.write("                                            href=\"viewBookingHistory?userLoginId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.userRegistrationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Booking\r\n");
      out.write("                                            History</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <!-- Dropdown Menu -->\r\n");
      out.write("                                    <li class=\"nav-item dropdown mx-3\">\r\n");
      out.write("                                        <a class=\"nav-link dropdown-toggle btn btn-primary text-light\" href=\"#\"\r\n");
      out.write("                                            id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                            aria-expanded=\"false\">\r\n");
      out.write("                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("                                            <li><a class=\"dropdown-item\"\r\n");
      out.write("                                                    href=\"editUserProfile?emailId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Profile</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a class=\"dropdown-item\"\r\n");
      out.write("                                                    href=\"getLogout?emailId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Log out</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal fade\" id=\"profileImageModal\" tabindex=\"-1\" aria-labelledby=\"profileImageModalLabel\"\r\n");
      out.write("                    aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog modal-sm  modal-dialog-centered\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"profileImageModalLabel\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'s\r\n");
      out.write("                                    Profile</h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                                    aria-label=\"Close\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <img src=\"getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.userImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"card-img-top\"\r\n");
      out.write("                                        alt=\"User Image\">\r\n");
      out.write("                                    <div class=\"card-body text-center\">\r\n");
      out.write("                                        <h5 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row justify-content-center py-3 my-5 mb-4\">\r\n");
      out.write("                    <div class=\"  col-12 col-md-6 \"> <!-- Increased card size -->\r\n");
      out.write("                        <div class=\"card p-5 mx-auto  rounded-0 shadow-lg hover-shadow-lg border-dark\"\r\n");
      out.write("                            style=\"background-color: rgba(231, 234, 248, 0.7);\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card-header text-center bg-transparent border-0\">\r\n");
      out.write("                                <h2 class=\"text-dark\">User Details</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4 class=\"text-center text-bold mt-3 mb-3 \" style=\"color: red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserUpdateMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4 text-center\">\r\n");
      out.write("                                <img src=\"getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.userImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Profile Image\"\r\n");
      out.write("                                    class=\"img-thumbnail rounded-circle shadow-lg border  border-warning\"\r\n");
      out.write("                                    style=\"width: 180px; height: 180px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"updateUserProfile\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                <input type=\"number\" name=\"userRegistrationId\"\r\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.userRegistrationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 1: First Name, Last Name -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">First Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"fName\" name=\"firstName\" placeholder=\"Enter First Name\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onblur=\"fNameValidation()\">\r\n");
      out.write("                                        <span id=\"firstName\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Last Name</label>\r\n");
      out.write("                                        <input type=\"text\" id=\"lName\" name=\"lastName\" placeholder=\"Enter Last Name\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            onblur=\"lNameValidation()\">\r\n");
      out.write("                                        <span id=\"lastName\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 2: Birth Date, Email ID -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Birth Date:</label>\r\n");
      out.write("                                        <input type=\"date\" id=\"birthDate\" name=\"birthdayDate\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.birthdayDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Email ID</label>\r\n");
      out.write("                                        <input type=\"email\" id=\"eId\" name=\"emailId\" placeholder=\"Enter Email Id\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\" onblur=\"checkEmail()\">\r\n");
      out.write("                                        <span id=\"emailId\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Row 3: Mobile Number,Gender -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">Mobile Number</label>\r\n");
      out.write("                                        <input type=\"tel\" id=\"mNumber\" name=\"mobileNumber\"\r\n");
      out.write("                                            placeholder=\"Enter Mobile Number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.mobileNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\"\r\n");
      out.write("                                            onblur=\"checkMobileNumber()\">\r\n");
      out.write("                                        <span id=\"mobileNumber\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-md-6\">\r\n");
      out.write("                                        <label class=\"form-label\">gender </label>\r\n");
      out.write("                                        <input type=\"text\" id=\"gen\" name=\"gender\" placeholder=\" Enter gender\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verifyUserOtpDto.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\">\r\n");
      out.write("                                        <span id=\"gender\" class=\"text-danger\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Row 4: File  -->\r\n");
      out.write("                                <div class=\"row g-3 gx-5 mb-4\">\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <label class=\"form-label\">Upload Profile Image</label>\r\n");
      out.write("                                        <input type=\"file\" id=\"file\" name=\"file\"\r\n");
      out.write("                                            class=\"form-control shadow-sm border border-dark\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Submit Button -->\r\n");
      out.write("                                <div class=\"text-center mt-4\">\r\n");
      out.write("                                    <button id=\"button\" type=\"submit\" class=\"btn btn-primary w-100 py-2 shadow\">Update\r\n");
      out.write("                                        Profile</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Footer -->\r\n");
      out.write("                <footer class=\"  text-light py-4 p-3  mt-4 text-center vw-100 \" style=\"background-color: rgb(6, 8, 8);\">\r\n");
      out.write("                    <div class=\"container-fluid\">\r\n");
      out.write("                        <p class=\"mb-2\">For assistance, email us at <strong>support@namma.metro.in</strong></p>\r\n");
      out.write("                        <p class=\"mb-2\">&copy; 2024 Namma Metro. All rights reserved.</p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"#\"><img src=\"https://img.icons8.com/ios-glyphs/30/ffffff/facebook-new.png\"\r\n");
      out.write("                                    alt=\"Facebook\"></a>\r\n");
      out.write("                            <a href=\"#\"><img src=\"https://img.icons8.com/ios-glyphs/30/ffffff/twitter.png\"\r\n");
      out.write("                                    alt=\"Twitter\"></a>\r\n");
      out.write("                            <a href=\"#\"><img src=\"https://img.icons8.com/ios-glyphs/30/ffffff/instagram-new.png\"\r\n");
      out.write("                                    alt=\"Instagram\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </footer>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function fNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"fName\").value;\r\n");
      out.write("                        console.log(names);\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 3 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        } else if (/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:yellow;'>firstName cannot contain numbers.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            document.getElementById(\"firstName\").innerHTML = \"<span style='color:yellow;'>Must be between 4 & 25 characters.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function lNameValidation() {\r\n");
      out.write("                        var names = document.getElementById(\"lName\").value;\r\n");
      out.write("                        console.log(names)\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        if (names.trim() !== '' && names.length > 0 && names.length <= 25 && !/\\d/.test(names)) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"Disabled\");\r\n");
      out.write("                        } else if (/\\d/.test(names) || names.length < 1) {\r\n");
      out.write("                            document.getElementById(\"lastName\").innerHTML = \"<span style='color:yellow;'>Last name cannot be a number and must be atleast 1.</span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    const checkMobileNumber = async () => {\r\n");
      out.write("                        var mNumber = document.getElementById(\"mNumber\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var mobileNumber = document.getElementById(\"mobileNumber\");\r\n");
      out.write("                        if (mNumber.length < 10 || mNumber.length > 10) {\r\n");
      out.write("                            mobileNumber.innerHTML = \"<span style='color:yellow'> Mobile Number length should be 10</span>\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            var response = await axios('http://localhost:8083/metro-application/isMobileNoExists?mobileNumber=' + mNumber);\r\n");
      out.write("                            if (response.data === \"Mobile Number Exists\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"<span style='color:yellow'> Mobile Number Exists</span>\";\r\n");
      out.write("                                button.removeAttribute(\"disabled\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if (response.data === \"Mobile Number Accepted\") {\r\n");
      out.write("                                mobileNumber.innerHTML = \"\";\r\n");
      out.write("                                button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    const checkEmail = async () => {\r\n");
      out.write("                        var email = document.getElementById(\"eId\").value;\r\n");
      out.write("                        var button = document.getElementById(\"button\");\r\n");
      out.write("                        var response = await axios('http://localhost:8083/metro-application/isUserEmailExists?emailId=' + email);\r\n");
      out.write("                        if (response.data === \"Email Exists\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"<span style ='color:yellow'> Email exists </span>\";\r\n");
      out.write("                            button.setAttribute(\"disabled\", \"\");\r\n");
      out.write("\r\n");
      out.write("                        } else if (response.data === \"Email Does not exists\") {\r\n");
      out.write("                            document.getElementById(\"emailId\").innerHTML = \"\";\r\n");
      out.write("                            button.removeAttribute(\"disabled\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\">\r\n");
      out.write("                </script>\r\n");
      out.write("                <script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
