/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-23 11:05:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NEW/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Montserrat:wght@300;400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Government Metro Service Login</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url('https://www.googleapis.com/download/storage/v1/b/kaggle-user-content/o/inbox%2F14601120%2F818e48829e36eb2016662b44dfc55937%2Fbanner04.jpg?generation=1691950460844130&alt=media');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom Metro Card */\r\n");
      out.write("        .metro-card {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 60px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .metro-card h2 {\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            text-shadow: 1px 1px 5px rgba(0, 0, 0, 0.7);\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .metro-card p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Custom Button */\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background-color: #ff6f61;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            transition: background-color 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            background-color: #ff5a4e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Form Inputs */\r\n");
      out.write("        .form-control {\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border: 2px solid #ccc;\r\n");
      out.write("            transition: border 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: #ff6f61;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(255, 111, 97, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand img {\r\n");
      out.write("            max-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link {\r\n");
      out.write("            color: white !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link:hover {\r\n");
      out.write("            background-color: #ff6f61;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 30px 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer a {\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"getIndex\">\r\n");
      out.write("                <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Metro Logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-light text-dark\" href=\"getLoginPage\">Back</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Namma Metro Corporation Custom Card -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"metro-card\">\r\n");
      out.write("            <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw-aNLlRb7L5prZL2byTNKoT2nH20mBHiN9A&s\" alt=\"Namma Metro Logo\" class=\"mb-3\" style=\"max-width: 300px; max-height: 150px;\">\r\n");
      out.write("            <h2>Welcome to Namma Metro Corporation</h2>\r\n");
      out.write("            <p>Experience a smooth and seamless metro service designed for the citizens of Bangalore. We are committed to providing safe, clean, and efficient transportation for all.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Login Form -->\r\n");
      out.write("    <div class=\"container my-5\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-6 col-lg-5\">\r\n");
      out.write("                <div class=\"card p-4 shadow-lg rounded\">\r\n");
      out.write("                    <h2 class=\"text-center mb-4\">User Login</h2>\r\n");
      out.write("                    <form action=\"getUserOtpDetails\" method=\"get\">\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <label for=\"userEmail\" class=\"form-label\">Email ID</label>\r\n");
      out.write("                            <input type=\"email\" id=\"userEmail\" name=\"emailId\" class=\"form-control shadow-sm\" placeholder=\"Enter your email ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required onblur=\"checkUserEmail()\">\r\n");
      out.write("                            <span id=\"ueId\" class=\"text-danger small\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-grid\">\r\n");
      out.write("                            <button type=\"submit\" id=\"button\" class=\"btn btn-custom rounded-pill\">✈️ Get OTP</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <div  class=\"text-center text-success mt-3\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OtpMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <form action=\"verifyUserOtp\" method=\"post\" class=\"mt-4\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"otp\" class=\"form-label\">Enter OTP</label>\r\n");
      out.write("                            <input type=\"hidden\" name=\"emailId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDto.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <input type=\"password\" id=\"otp\" name=\"otp\" class=\"form-control shadow-sm\" placeholder=\"Enter your OTP\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-grid\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-success rounded-pill\">Login</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <a href=\"#\" class=\"mx-3\">Privacy Policy</a>\r\n");
      out.write("                <a href=\"#\" class=\"mx-3\">Terms of Service</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"mb-0\">&copy; 2024 Government Metro Service. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        const checkUserEmail = async () => {\r\n");
      out.write("            const email = document.getElementById(\"userEmail\").value;\r\n");
      out.write("            const button = document.getElementById(\"button\");\r\n");
      out.write("            const ueId = document.getElementById(\"ueId\");\r\n");
      out.write("            ueId.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("            if (email.length < 5) {\r\n");
      out.write("                ueId.innerHTML = \"<span class='text-danger'>Invalid email</span>\";\r\n");
      out.write("                button.setAttribute(\"disabled\", \"true\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("             console.log(\"email  is ================== \"+email);\r\n");
      out.write("            const response = await axios('http://localhost:8083/metro-application/isUserEmailExists?emailId='+email);\r\n");
      out.write("            console.log(\"email  is ================== \"+email);\r\n");
      out.write("            console.log(\"email response is ================== \"+response.data);\r\n");
      out.write("            if (response.data === \"Email Exists\") {\r\n");
      out.write("                console.log(\"email response if exists  is ================== \"+response.data);\r\n");
      out.write("                ueId.innerHTML = \"\";\r\n");
      out.write("                button.removeAttribute(\"disabled\");\r\n");
      out.write("            } else {\r\n");
      out.write("                console.log(\"email response if not exists  is ================== \"+response.data);\r\n");
      out.write("                ueId.innerHTML = \"<span class='text-danger'>Email does not exist</span>\";\r\n");
      out.write("                button.setAttribute(\"disabled\", \"true\");\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
